// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Prisma 7: connection URL lives here for CLI/Migrate (not in schema.prisma).
  // The runtime PrismaClient is given the same URL via `accelerateUrl` (see lib/db.ts),
  // since DATABASE_URL uses the prisma+postgres:// (Accelerate) protocol.
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
